### ISSUE TITLE
Rename Pins

### ISSUE THREAD

**Issue by bigboateng** [tylerjackoliver/LunarHopper#3]
need to change the un-named pins when we know what they do. [Check this file](https://github.com/tylerjackoliver/LunarHopper/blob/master/Mk2.1_hopper_control.ino#L193-198)

**Comment by tylerjackoliver** [comment]
Unnamed pins were renamed in commit c3c12a11de7ddbf1ebb9072c8c89a552c9bad47e.

**Comment by bigboateng** [comment]
1. On the [Master Branch](https://github.com/tylerjackoliver/LunarHopper/blob/master/Mk2.1_hopper_control.ino#L193-198), the change is not there, which branch was that commit in?
2. Maybe we should actually rename the pins as variables because its still not clear what testing pins that is.

**Comment by tylerjackoliver** [comment]
You're correct; the pins were commented out in the setup() of c3c12a11de7ddbf1ebb9072c8c89a552c9bad47e. Need to go through master and remove all references to pins 7, 8, 9, 24, 26, 28 in loop() as they are obsolete.

**Comment by tylerjackoliver** [comment]
Pins were removed in commit cf2e08ffbd0063617e6673bff230312deaae3e4f in branch RemovedPins.

**Comment by duncanrhamill** [comment]
Pins 7, 8 & 9 might be used for testing the ox pulse onto the catalyst bed, need to verify if they're needed in flight or just in test.

**Comment by tylerjackoliver** [comment]
I spoke with Marian, who wrote the code: we had the right purpose for the pins and were correct to remove them in commit cf2e08ffbd0063617e6673bff230312deaae3e4f.

**Comment by bigboateng** [comment]
So is this issue settled then? @tylerjackoliver
