### ISSUE TITLE
Verify ox_pulse() is redundant 

### ISSUE THREAD

**Issue by tylerjackoliver** [tylerjackoliver/LunarHopper#9]

**Comment by bigboateng** [comment]
What does that function do?

**Comment by duncanrhamill** [comment]
Not only does it look redundant, looks like it won't work at all. It waits until the system is pressurised, but it never calls the pressurise function, and pressurise() isn't called in the main loop so there's no way ox_pulse() would ever actually do it's job.

**Comment by duncanrhamill** [comment]
Oh also we have another duplicate function, pressurization() and Pressurisation(). To me it looks like Pressurisation() is the good one as that's what ox_Pulse() calls.

**Comment by tylerjackoliver** [comment]
Yes, Pressurisation() is the only one that gets called. I'll update it and close this.
